# OPERADORES DE ARREGLOS

Los operadores en NumPy permiten realizar operaciones sencillas **sobre cada uno de los elementos de un arreglo**.

Veamos los principales operadores.

## OPERACIONES ARITMÉTICAS CON ESCALARES

Podemos usar los operadores simples de Python (como `+`, `-`, `*` y `**`) para realizar operaciones aritméticas entre un arreglo y un escalar:

In [1]:
import numpy as np

arreglo = np.arange(5,15)
print(arreglo)

[ 5  6  7  8  9 10 11 12 13 14]


In [3]:
# Sumar (o restar) la misma cantidad a cada elemento del arreglo
arreglo - 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
# También podemos lograr el mismo resultado anterior usando el operador +=
# pero en este caso la variable arreglo resulta modificada
print(arreglo)
arreglo += 2
print(arreglo)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7  8  9 10 11 12 13 14 15 16]


In [5]:
# Multiplicar cada elemento del arreglo por una misma cantidad
0.5*arreglo

array([3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [6]:
# Elevar cada elemento del arreglo a una potencia específica
arreglo**2

array([ 49,  64,  81, 100, 121, 144, 169, 196, 225, 256])

## OPERACIONES ARITMÉTICAS ENTRE ARREGLOS

Para realizar operaciones de este tipo **ambos arreglos deben tener el mismo tamaño**:

In [7]:
# Los arreglos 1 y 2 contienen 10 elementos, el arreglo 3 contiene 12 elementos
arreglo_1 = np.linspace(3,5,10)
arreglo_2 = np.linspace(7,9,10)
arreglo_3 = np.linspace(10,15,12)

In [8]:
# Podemos multiplicar elemento a elemento los arreglos 1 y 2,
# generando un nuevo arreglo de 10 elementos
arreglo_1 * arreglo_2

array([21.        , 23.27160494, 25.64197531, 28.11111111, 30.67901235,
       33.34567901, 36.11111111, 38.97530864, 41.9382716 , 45.        ])

In [10]:
# Pero NO podemos multiplicar los arreglos 1 y 3 o 2 y 3
arreglo_2 * arreglo_3

ValueError: operands could not be broadcast together with shapes (10,) (12,) 

In [11]:
# Y desde luego la multiplicación elemento a elemento la podemos extender a matrices
# siempre y cuando sean del mismo tamaño
matriz_1 = arreglo_1.reshape(5,2)
matriz_2 = arreglo_2.reshape(5,2)
matriz_multip = matriz_1*matriz_2
print(f'Tamaño matriz resultante: {matriz_multip.shape}')

Tamaño matriz resultante: (5, 2)


In [12]:
# Si multiplico un arreglo de enteros por uno de decimales el resultado
# es un arreglo de decimales (lo mismo ocurre con la suma o la resta)
arreglo_int = np.arange(0,10) # 10 elementos, del 0 al 9
arreglo_float = np.linspace(2,8,10) # 10 elementos entre 2 y 8
arreglos_mult = arreglo_int * arreglo_float

print(f'dtype arreglo 1: {arreglo_int.dtype}')
print(f'dtype arreglo 2: {arreglo_float.dtype}')
print(f'dtype arreglo resultante: {arreglos_mult.dtype}')

dtype arreglo 1: int64
dtype arreglo 2: float64
dtype arreglo resultante: float64


## OPERACIONES LÓGICAS

Se pueden aplicar operadores de comparación para comparar cada elemento del arreglo con un escalar o elemento a elemento (en el caso de comparar dos arreglos):

In [13]:
# Comparar cada elemento de un arreglo con un escalar
arreglo = np.linspace(5,50,20)
print(arreglo)

[ 5.          7.36842105  9.73684211 12.10526316 14.47368421 16.84210526
 19.21052632 21.57894737 23.94736842 26.31578947 28.68421053 31.05263158
 33.42105263 35.78947368 38.15789474 40.52631579 42.89473684 45.26315789
 47.63157895 50.        ]


In [14]:
# Determinar qué elementos son mayores o iguales que 25: el resultado es un
# arreglo del mismo tamaño original pero sus elementos serán variables
# booleanas (True o False)
arreglo >= 25

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [15]:
# Generar un segundo arreglo DEL MISMO TAMAÑO DEL ANTERIOR
arreglo_2 = np.linspace(4,60,20)
print(arreglo_2)

[ 4.          6.94736842  9.89473684 12.84210526 15.78947368 18.73684211
 21.68421053 24.63157895 27.57894737 30.52631579 33.47368421 36.42105263
 39.36842105 42.31578947 45.26315789 48.21052632 51.15789474 54.10526316
 57.05263158 60.        ]


In [16]:
# Y compararlo elemento a elemento con el primer arreglo para determinar cuáles
# elementos son mayores
arreglo_2 > arreglo

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
# O determinar si existen elementos iguales
arreglo_2 != arreglo

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])