# ATRIBUTOS BÁSICOS DE UN ARREGLO

Como vimos en la lección anterior, un arreglo de NumPy (sin importar sus dimensiones) es en últimas un tipo de dato `ndarray` en Python. ¡Es decir que un arreglo es un objeto!

Y por ser un objeto tendrá una serie de atributos. En esta lección veremos los principales atributos de un arreglo de NumPy.

In [1]:
import numpy as np

# Creemos inicialmente dos arreglos, uno con números enteros y otro con números decimales
a = np.array([[12, 25, 3],[7, 14, 92]])
b = np.array([5.1, 4.3, 8.2])

print(a)
print(b)

[[12 25  3]
 [ 7 14 92]]
[5.1 4.3 8.2]


## ATRIBUTO `dtype`

Indica el tipo de dato con el que está almacenado cada elemento del arreglo:

In [2]:
# El arreglo de enteros es de tipo "int64" (es decir que cada elemento está almacenado
# en memoria como un "entero con 64 bits")
a.dtype

dtype('int64')

In [3]:
# El arreglo de decimales es de tipo "float64" (es decir que cada elemento está almacenado
# en memoria en formato "punto flotante con 64 bits")
b.dtype

dtype('float64')

## ATRIBUTO `ndim`

Indica la dimensionalidad del arreglo:

In [2]:
# El arreglo "a" es de 2 dimensiones (es una matriz)
a.ndim

2

In [3]:
# Mientras que el arreglo "b" es de 1 dimensión (es un vector)
b.ndim

1

## ATRIBUTO `shape`

Indica el tamaño del arreglo (la cantidad de datos en cada una de las dimensiones):

In [6]:
# "a" es una matriz de 2 filas x 3 columnas
a.shape

(2, 3)

In [7]:
# "b" es simplemente un vector de 3 elementos
b.shape

(3,)

## ATRIBUTO `size`

Indica el número total de elementos del arreglo (independientemente de su dimensionalidad):

In [8]:
# "a" contiene un total de 2x3 = 6 elementos
a.size

6

In [9]:
# "b" contiene 3 elementos
b.size

3