# FUNCIONES PARA LA CREACIÓN DE ARREGLOS

Además de la forma básica de creación de arreglos haciendo uso del método `array`, NumPy incluye otras funciones para facilitar este proceso.

En esta lección veremos varias de estas alternativas.

## `zeros`, `ones` Y `full`

Permiten crear arreglos de cualquier tamaño con todos los valores iguales a cero (`zeros`), con todos los valores iguales a uno (`ones`) o con un valor específico (`full`).

In [2]:
import numpy as np

# Arreglo 3D con ceros
a = np.zeros((4,2,3)) # El tamaño del arreglo se especifica en una tupla: (dim1, dim2, dim3, etc.)
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [3]:
print(f'Dimensiones del arreglo: {a.ndim}')
print(f'Tamaño del arreglo: {a.shape}')
print(f'Número de elementos del arreglo: {a.size}')

Dimensiones del arreglo: 3
Tamaño del arreglo: (4, 2, 3)
Número de elementos del arreglo: 24


In [4]:
# Vector de unos pero de typo 'float64'
b = np.ones(7, dtype=float)
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [5]:
print(f'Dimensiones del arreglo: {b.ndim}')
print(f'Tipo de dato del arreglo: {b.dtype}')

Dimensiones del arreglo: 1
Tipo de dato del arreglo: float64


In [6]:
# Arreglo 2D con todos los valores iguales a 12 (formato float64)
c = np.full((5,2), 12.0)
print(c)

[[12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]
 [12. 12.]]


In [7]:
print(f'Dimensiones del arreglo: {c.ndim}')
print(f'Tamaño del arreglo: {c.shape}')
print(f'Tipo de dato del arreglo: {c.dtype}')

Dimensiones del arreglo: 2
Tamaño del arreglo: (5, 2)
Tipo de dato del arreglo: float64


## CREACIÓN DE ARREGLOS CON `arange` + EL MÉTODO `reshape`

La función `arange` permite generar un arreglo 1D con valores enteros en un rango específico:

In [8]:
arreglo_1 = np.arange(10) # Genera un vector con los números del 0 al 9
print(arreglo_1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arreglo_2 = np.arange(2,15) # Genera un vector con los números del 2 al 14
print(arreglo_2)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
arreglo_3 = np.arange(3,10,2) # Genera un vector con los números del 3 al 9 en pasos de a 2
print(arreglo_3)

[3 5 7 9]


Y podemos usar la función `reshape` para convertir el vector a un arreglo de 2 o más dimensiones. En este caso **el número de elementos del nuevo arreglo debe ser igual al número de elementos del vector original**:

In [11]:
arreglo_4 = np.arange(2,101,2)        # Vector con los números pares del 2 al 100 (50 elementos)
arreglo_5 = arreglo_4.reshape((5,10)) # Matriz de 5x10 con los números pares del 2 al 100
print(arreglo_4)
print(arreglo_5)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [12]:
# Y podemos obtener el mismo resultado anterior pero en una sola línea de código
arreglo_6 = np.arange(2,101,2).reshape((5,10))
print(arreglo_6)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


## CREACIÓN DE ARREGLOS CON `linspace` + EL MÉTODO `reshape`

La función `linspace` permite generar un arreglo 1D con valores decimales en un rango específico:

In [13]:
arreglo_7 = np.linspace(0,10,100) # Generar 100 valores en el rango de 0 a 10
print('El arreglo: ')
print(arreglo_7)
print(f'Tamaño del arreglo: {arreglo_7.shape}')

El arreglo: 
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  

In [14]:
# Y podemos usar reshape para generar una matriz
arreglo_8 = np.linspace(0,10,20).reshape((5,4))
arreglo_8

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737],
       [ 2.10526316,  2.63157895,  3.15789474,  3.68421053],
       [ 4.21052632,  4.73684211,  5.26315789,  5.78947368],
       [ 6.31578947,  6.84210526,  7.36842105,  7.89473684],
       [ 8.42105263,  8.94736842,  9.47368421, 10.        ]])